import type {
  AircraftMarketplaceDetail,
  AircraftMarketplaceListing,
} from "./aircraft-marketplace-types";

const IMG = {
  cessna172:
    "https://images.unsplash.com/photo-1436491865332-7a61a4cc60fc?auto=format&fit=crop&w=1200&q=80",
  piper:
    "https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=1200&q=80",
  cirrus:
    "https://images.unsplash.com/photo-1569629743817-70d8db44c474?auto=format&fit=crop&w=1200&q=80",
  beech:
    "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=1200&q=80",
  sling:
    "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=80",
  cockpit:
    "https://images.unsplash.com/photo-1517976487492-5750f3195933?auto=format&fit=crop&w=1200&q=80",
  engine:
    "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80",
  helicopter:
    "https://images.unsplash.com/photo-1508614999362-7fbc978a75e5?auto=format&fit=crop&w=1200&q=80",
  turboprop:
    "https://images.unsplash.com/photo-1556388158-158ea5ccad2f?auto=format&fit=crop&w=1200&q=80",
};

function images(
  primary: string,
  extras: string[],
  registration: string,
): AircraftMarketplaceListing["images"] {
  return [
    { id: "1", url: primary, alt: `${registration} exterior`, isPrimary: true, slotKey: "exterior_front_45" },
    ...extras.map((url, index) => ({
      id: String(index + 2),
      url,
      alt: `${registration} photo ${index + 2}`,
    })),
  ];
}

const MOCK_LISTINGS: AircraftMarketplaceDetail[] = [
  {
    id: "lst-001",
    slug: "zs-abc-cessna-172n",
    registration: "ZS-ABC",
    year: 1978,
    make: "Cessna",
    model: "172N",
    variant: "Skyhawk",
    category: "SINGLE_ENGINE_PISTON",
    saleType: "FIXED_PRICE",
    publicStatus: "AVAILABLE",
    price: 1_250_000,
    currency: "ZAR",
    location: { airfield: "Morningstar", province: "Western Cape", country: "South Africa" },
    totalTimeAirframe: 2840,
    engineTime: 180,
    engineTimeLabel: "SMOH",
    seats: 4,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "IFR",
    maintenanceSummary: "MPI current · Hangared",
    highlights: [
      "MPI current",
      "Hangared",
      "Complete logbooks",
      "Garmin avionics",
      "IFR equipped",
      "No known damage history",
    ],
    images: images(IMG.cessna172, [IMG.cockpit, IMG.engine, IMG.piper], "ZS-ABC"),
    isVerified: true,
    isFeatured: true,
    listedAt: "2026-03-15T08:00:00.000Z",
    updatedAt: "2026-03-28T10:00:00.000Z",
    description:
      "Well-maintained Cessna 172N based at Morningstar Airfield. Used primarily for local training and family cross-country flying. Always hangared, complete logbooks, and recent MPI. Ideal for a private owner or flight school upgrade.",
    technicalSpec: {
      airframe: {
        totalTimeAirframe: 2840,
        yearOfManufacture: 1978,
        serialNumber: "172-68421",
        category: "Single Engine Piston",
        registrationType: "ZS",
        damageHistory: "No known damage history",
        accidentHistory: "None recorded",
        paintCondition: "Good — recent touch-ups",
        interiorCondition: "Good — seats re-trimmed 2023",
      },
      engines: [
        {
          position: "Centre",
          manufacturer: "Lycoming",
          model: "O-320-H2AD",
          engineHours: 2840,
          timeSinceOverhaul: 180,
          overhaulDate: "2024-06",
          knownIssues: "None disclosed",
        },
      ],
      propeller: {
        manufacturer: "McCauley",
        model: "1A175",
        bladeCount: 2,
        propellerType: "Fixed pitch",
        propellerHours: 180,
        timeSinceOverhaul: 180,
      },
      avionics: {
        primarySuite: "Garmin GNS 430W + G5",
        comRadios: "Garmin SL30",
        navRadios: "Garmin GNS 430W",
        transponder: "Garmin GTX 327",
        adsB: "ADS-B Out equipped",
        gps: "Garmin GNS 430W",
        autopilot: "Not fitted",
        engineMonitor: "JPI 700",
        elt: "406 MHz",
      },
      maintenance: {
        lastMpiDate: "2025-11-12",
        nextMpiDueDate: "2026-11-12",
        maintenanceOrganisation: "Morningstar AMO",
        logbooksComplete: true,
        airframeLogsAvailable: true,
        engineLogsAvailable: true,
        propellerLogsAvailable: true,
        currentlyAirworthy: true,
        knownDefects: "Minor paint chips on wing tips",
      },
    },
    documents: [
      { label: "Certificate of Registration", status: "Available on request" },
      { label: "Authority to Fly / CoA", status: "Reviewed by AVIATONLY" },
      { label: "Maintenance records", status: "Available to verified buyers" },
      { label: "Logbook summary", status: "Available to verified buyers" },
    ],
    verification: {
      documentsReviewed: true,
      photosVerified: true,
      inspectionAvailable: true,
      notes: "Seller documents reviewed. Independent inspection available on request.",
    },
    marketEstimate: {
      available: true,
      minValue: 1_150_000,
      maxValue: 1_350_000,
      currency: "ZAR",
      marketPosition: "Fairly priced",
      notes: "Based on aircraft type, hours, avionics, maintenance status, and comparable listings.",
    },
    contact: {
      sellerType: "AVIATONLY",
      contactName: "AVIATONLY Listings Team",
      email: "listings@aviatonly.co.za",
      phone: "+27 21 000 0000",
    },
  },
  {
    id: "lst-002",
    slug: "zs-def-piper-archer",
    registration: "ZS-DEF",
    year: 2005,
    make: "Piper",
    model: "PA-28-181",
    variant: "Archer III",
    category: "SINGLE_ENGINE_PISTON",
    saleType: "FIXED_PRICE",
    publicStatus: "NEW_LISTING",
    price: 2_100_000,
    currency: "ZAR",
    location: { airfield: "Wonderboom", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 1650,
    engineTime: 420,
    engineTimeLabel: "SMOH",
    seats: 4,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "Garmin G1000",
    maintenanceSummary: "Logbooks complete",
    highlights: ["Garmin G1000", "Autopilot", "ADS-B Out", "Low engine time", "Fresh annual"],
    images: images(IMG.piper, [IMG.cockpit, IMG.cessna172], "ZS-DEF"),
    isVerified: true,
    listedAt: "2026-03-25T08:00:00.000Z",
    updatedAt: "2026-03-27T14:00:00.000Z",
    description:
      "Low-time Piper Archer III with Garmin G1000 glass cockpit. Excellent platform for IFR training or personal travel. Complete maintenance history with Wonderboom AMO.",
    technicalSpec: {
      airframe: {
        totalTimeAirframe: 1650,
        yearOfManufacture: 2005,
        serialNumber: "28-43102",
        category: "Single Engine Piston",
        registrationType: "ZS",
        damageHistory: "No known damage history",
        paintCondition: "Excellent",
        interiorCondition: "Very good",
      },
      engines: [
        {
          position: "Centre",
          manufacturer: "Lycoming",
          model: "O-360-A4M",
          timeSinceOverhaul: 420,
        },
      ],
      avionics: {
        primarySuite: "Garmin G1000",
        autopilot: "Garmin GFC 700",
        adsB: "ADS-B Out/In",
        gps: "Integrated G1000",
      },
      maintenance: {
        lastMpiDate: "2026-01-20",
        logbooksComplete: true,
        currentlyAirworthy: true,
      },
    },
    documents: [
      { label: "Certificate of Registration", status: "Reviewed by AVIATONLY" },
      { label: "Maintenance records", status: "Available to verified buyers" },
    ],
    verification: { documentsReviewed: true, photosVerified: true, inspectionAvailable: true },
    marketEstimate: {
      available: true,
      minValue: 1_950_000,
      maxValue: 2_250_000,
      currency: "ZAR",
      marketPosition: "Fairly priced",
    },
    contact: { sellerType: "BROKER", contactName: "Highveld Aviation Brokers", email: "sales@highveld.co.za" },
  },
  {
    id: "lst-003",
    slug: "zs-ghi-cirrus-sr22",
    registration: "ZS-GHI",
    year: 2018,
    make: "Cirrus",
    model: "SR22",
    variant: "G6",
    category: "SINGLE_ENGINE_PISTON",
    saleType: "MAKE_OFFER",
    publicStatus: "AVAILABLE",
    priceLabel: "Offers from R4.5m",
    currency: "ZAR",
    location: { airfield: "Lanseria", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 980,
    engineTime: 980,
    engineTimeLabel: "TSN",
    seats: 4,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "Cirrus Perspective+",
    maintenanceSummary: "Hangared · MPI current",
    highlights: ["Cirrus Airframe Parachute System", "Garmin Perspective+", "IFR equipped", "Always hangared"],
    images: images(IMG.cirrus, [IMG.cockpit, IMG.engine, IMG.beech], "ZS-GHI"),
    isVerified: true,
    isFeatured: true,
    listedAt: "2026-02-10T08:00:00.000Z",
    updatedAt: "2026-03-20T09:00:00.000Z",
    description:
      "Premium Cirrus SR22 G6 with Perspective+ avionics and CAPS. Hangared since new, single-owner aircraft used for business travel within South Africa.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 980, yearOfManufacture: 2018, registrationType: "ZS" },
      engines: [{ position: "Centre", manufacturer: "Continental", model: "IO-550-N", timeSinceNew: 980 }],
      avionics: { primarySuite: "Garmin Perspective+", autopilot: "Garmin GFC 700", adsB: "ADS-B Out/In" },
      maintenance: { lastMpiDate: "2025-09-01", logbooksComplete: true, currentlyAirworthy: true },
    },
    documents: [
      { label: "Certificate of Registration", status: "Available on request" },
      { label: "Authority to Fly / CoA", status: "Reviewed by AVIATONLY" },
    ],
    verification: { documentsReviewed: true, photosVerified: true, inspectionCompleted: true },
    marketEstimate: {
      available: true,
      minValue: 4_200_000,
      maxValue: 4_800_000,
      currency: "ZAR",
      marketPosition: "Premium listing",
    },
    contact: { sellerType: "PRIVATE", contactName: "Private seller", email: "enquiries via AVIATONLY" },
  },
  {
    id: "lst-004",
    slug: "zs-jkl-beech-bonanza",
    registration: "ZS-JKL",
    year: 1992,
    make: "Beechcraft",
    model: "A36",
    variant: "Bonanza",
    category: "SINGLE_ENGINE_PISTON",
    saleType: "FIXED_PRICE",
    publicStatus: "UNDER_OFFER",
    price: 3_450_000,
    currency: "ZAR",
    location: { airfield: "Stellenbosch", province: "Western Cape", country: "South Africa" },
    totalTimeAirframe: 3200,
    engineTime: 650,
    seats: 6,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "IFR · Autopilot",
    maintenanceSummary: "Inspection available",
    highlights: ["Six seats", "Long-range tanks", "IFR equipped", "Autopilot", "Inspection available"],
    images: images(IMG.beech, [IMG.cockpit, IMG.cessna172], "ZS-JKL"),
    isVerified: true,
    listedAt: "2026-01-05T08:00:00.000Z",
    updatedAt: "2026-03-29T11:00:00.000Z",
    description: "Capable cross-country Bonanza A36 with long-range tanks and IFR avionics. Under offer — backup enquiries welcome.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 3200, yearOfManufacture: 1992 },
      engines: [{ position: "Centre", manufacturer: "Continental", model: "IO-550-B", timeSinceOverhaul: 650 }],
      avionics: { primarySuite: "Garmin GNS 530 + KFC 150", autopilot: "Bendix/King KFC 150" },
      maintenance: { logbooksComplete: true, currentlyAirworthy: true },
    },
    documents: [{ label: "Maintenance records", status: "Available to verified buyers" }],
    verification: { documentsReviewed: true, photosVerified: true, inspectionAvailable: true },
    marketEstimate: { available: true, minValue: 3_200_000, maxValue: 3_600_000, currency: "ZAR", marketPosition: "Fairly priced" },
    contact: { sellerType: "BROKER", contactName: "Cape Aviation Sales", phone: "+27 21 555 0101" },
  },
  {
    id: "lst-005",
    slug: "zu-mno-sling-4",
    registration: "ZU-MNO",
    year: 2021,
    make: "Sling",
    model: "4",
    category: "LIGHT_SPORT",
    saleType: "FIXED_PRICE",
    publicStatus: "AVAILABLE",
    price: 1_850_000,
    currency: "ZAR",
    location: { airfield: "Tedderfield", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 420,
    engineTime: 420,
    seats: 4,
    engineCount: 1,
    registrationType: "ZU",
    avionicsSummary: "Glass cockpit",
    maintenanceSummary: "Logbooks complete",
    highlights: ["Low total time", "Glass cockpit", "South African manufactured", "Complete logbooks"],
    images: images(IMG.sling, [IMG.cockpit, IMG.engine], "ZU-MNO"),
    isVerified: false,
    listedAt: "2026-03-01T08:00:00.000Z",
    updatedAt: "2026-03-22T08:00:00.000Z",
    description: "Low-time Sling 4 LSA ideal for recreational flying and cross-country touring.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 420, registrationType: "ZU" },
      engines: [{ position: "Centre", manufacturer: "Rotax", model: "912 ULS" }],
      avionics: { primarySuite: "MGL Avionics", efis: "MGL EFIS" },
      maintenance: { logbooksComplete: true, currentlyAirworthy: true },
    },
    documents: [{ label: "Authority to Fly", status: "Available on request" }],
    verification: { photosVerified: true, inspectionAvailable: true },
    marketEstimate: { available: false, notes: "AVIATONLY can provide a valuation once the aircraft has been reviewed." },
    contact: { sellerType: "PRIVATE", contactName: "Private seller" },
  },
  {
    id: "lst-006",
    slug: "zs-pqr-robinson-r44",
    registration: "ZS-PQR",
    year: 2016,
    make: "Robinson",
    model: "R44",
    variant: "Raven II",
    category: "HELICOPTER",
    saleType: "PRICE_ON_APPLICATION",
    publicStatus: "AVAILABLE",
    priceLabel: "Price on application",
    currency: "ZAR",
    location: { airfield: "Grand Central", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 1450,
    engineTime: 450,
    seats: 4,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "Garmin G500H",
    maintenanceSummary: "MPI current",
    highlights: ["Garmin G500H", "MPI current", "Touring configuration", "Hangared"],
    images: images(IMG.helicopter, [IMG.cockpit, IMG.engine], "ZS-PQR"),
    isVerified: true,
    listedAt: "2026-02-20T08:00:00.000Z",
    updatedAt: "2026-03-18T08:00:00.000Z",
    description: "Robinson R44 Raven II suitable for touring and utility work. POA — qualified buyers may request pricing and documentation.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 1450, category: "Helicopter" },
      engines: [{ position: "Main", manufacturer: "Lycoming", model: "IO-540-AE1A5", timeSinceOverhaul: 450 }],
      avionics: { primarySuite: "Garmin G500H" },
      maintenance: { lastMpiDate: "2025-12-01", currentlyAirworthy: true },
    },
    documents: [{ label: "Maintenance records", status: "Available on request" }],
    verification: { documentsReviewed: true, inspectionAvailable: true },
    marketEstimate: { available: false },
    contact: { sellerType: "AVIATONLY", contactName: "AVIATONLY Helicopter Desk", email: "helicopters@aviatonly.co.za" },
  },
  {
    id: "lst-007",
    slug: "zs-stu-king-air-c90",
    registration: "ZS-STU",
    year: 1985,
    make: "Beechcraft",
    model: "King Air",
    variant: "C90",
    category: "TURBOPROP",
    saleType: "FIXED_PRICE",
    publicStatus: "AVAILABLE",
    price: 8_500_000,
    currency: "ZAR",
    location: { airfield: "Lanseria", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 8900,
    engineTime: 1200,
    seats: 8,
    engineCount: 2,
    registrationType: "ZS",
    avionicsSummary: "Pro Line 21",
    maintenanceSummary: "Corporate maintained",
    highlights: ["Twin turboprop", "Pro Line 21", "Corporate history", "Inspection available"],
    images: images(IMG.turboprop, [IMG.cockpit, IMG.beech, IMG.engine], "ZS-STU"),
    isVerified: true,
    listedAt: "2025-12-01T08:00:00.000Z",
    updatedAt: "2026-03-10T08:00:00.000Z",
    description: "King Air C90 with corporate maintenance pedigree. Suitable for owner-operator or charter upgrade.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 8900, category: "Turboprop" },
      engines: [
        { position: "Left", manufacturer: "Pratt & Whitney", model: "PT6A-21", timeSinceOverhaul: 1200 },
        { position: "Right", manufacturer: "Pratt & Whitney", model: "PT6A-21", timeSinceOverhaul: 1180 },
      ],
      avionics: { primarySuite: "Collins Pro Line 21", autopilot: "Collins APS-65" },
      maintenance: { logbooksComplete: true, currentlyAirworthy: true },
    },
    documents: [
      { label: "Certificate of Registration", status: "Reviewed by AVIATONLY" },
      { label: "Maintenance records", status: "Available to verified buyers" },
    ],
    verification: { documentsReviewed: true, photosVerified: true, inspectionAvailable: true },
    marketEstimate: {
      available: true,
      minValue: 7_800_000,
      maxValue: 9_200_000,
      currency: "ZAR",
      marketPosition: "Fairly priced",
    },
    contact: { sellerType: "BROKER", contactName: "Executive Turbine Sales" },
  },
  {
    id: "lst-008",
    slug: "zs-vwx-diamond-da40",
    registration: "ZS-VWX",
    year: 2010,
    make: "Diamond",
    model: "DA40",
    variant: "XLS",
    category: "SINGLE_ENGINE_PISTON",
    saleType: "FIXED_PRICE",
    publicStatus: "AVAILABLE",
    price: 2_750_000,
    currency: "ZAR",
    location: { airfield: "George", province: "Western Cape", country: "South Africa" },
    totalTimeAirframe: 2100,
    engineTime: 310,
    seats: 4,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "Garmin G1000",
    maintenanceSummary: "Hangared",
    highlights: ["Garmin G1000", "Composite airframe", "Hangared", "IFR equipped"],
    images: images(IMG.cirrus, [IMG.cockpit, IMG.cessna172], "ZS-VWX"),
    listedAt: "2026-03-12T08:00:00.000Z",
    updatedAt: "2026-03-26T08:00:00.000Z",
    description: "Diamond DA40 XLS with G1000 and excellent fuel economy. Based in George with coastal flying history.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 2100 },
      engines: [{ position: "Centre", manufacturer: "Lycoming", model: "IO-360-M1A", timeSinceOverhaul: 310 }],
      avionics: { primarySuite: "Garmin G1000" },
      maintenance: { currentlyAirworthy: true, logbooksComplete: true },
    },
    documents: [{ label: "Logbook summary", status: "Available on request" }],
    verification: { photosVerified: true, inspectionAvailable: true },
    marketEstimate: { available: true, minValue: 2_550_000, maxValue: 2_900_000, currency: "ZAR", marketPosition: "Fairly priced" },
    contact: { sellerType: "PRIVATE", contactName: "Private seller" },
  },
  {
    id: "lst-009",
    slug: "zs-yza-mooney-m20j",
    registration: "ZS-YZA",
    year: 1988,
    make: "Mooney",
    model: "M20J",
    variant: "201",
    category: "SINGLE_ENGINE_PISTON",
    saleType: "FIXED_PRICE",
    publicStatus: "AVAILABLE",
    price: 1_650_000,
    currency: "ZAR",
    location: { airfield: "Virginia", province: "KwaZulu-Natal", country: "South Africa" },
    totalTimeAirframe: 4100,
    engineTime: 890,
    seats: 4,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "IFR",
    maintenanceSummary: "MPI current",
    highlights: ["Fast cruiser", "IFR equipped", "MPI current", "Complete logbooks"],
    images: images(IMG.beech, [IMG.cockpit], "ZS-YZA"),
    listedAt: "2026-03-08T08:00:00.000Z",
    updatedAt: "2026-03-24T08:00:00.000Z",
    description: "Mooney M20J known for efficient cross-country performance. IFR equipped with recent MPI.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 4100 },
      engines: [{ position: "Centre", manufacturer: "Lycoming", model: "IO-360-A1B6", timeSinceOverhaul: 890 }],
      avionics: { primarySuite: "Garmin GNS 430", gps: "Garmin GNS 430" },
      maintenance: { lastMpiDate: "2025-10-15", currentlyAirworthy: true },
    },
    documents: [{ label: "Maintenance records", status: "Available on request" }],
    verification: { inspectionAvailable: true },
    marketEstimate: { available: true, minValue: 1_500_000, maxValue: 1_750_000, currency: "ZAR", marketPosition: "Fairly priced" },
    contact: { sellerType: "PRIVATE", contactName: "Private seller" },
  },
  {
    id: "lst-010",
    slug: "zs-bcd-tecnam-p2002",
    registration: "ZS-BCD",
    year: 2014,
    make: "Tecnam",
    model: "P2002",
    variant: "Sierra",
    category: "LIGHT_SPORT",
    saleType: "FIXED_PRICE",
    publicStatus: "AVAILABLE",
    price: 950_000,
    currency: "ZAR",
    location: { airfield: "Morningstar", province: "Western Cape", country: "South Africa" },
    totalTimeAirframe: 780,
    engineTime: 780,
    seats: 2,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "VFR",
    maintenanceSummary: "Logbooks complete",
    highlights: ["Light sport", "Low operating cost", "Training platform", "Complete logbooks"],
    images: images(IMG.sling, [IMG.cockpit], "ZS-BCD"),
    listedAt: "2026-03-20T08:00:00.000Z",
    updatedAt: "2026-03-29T08:00:00.000Z",
    description: "Affordable Tecnam P2002 Sierra for club or private recreational use.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 780 },
      engines: [{ position: "Centre", manufacturer: "Rotax", model: "912 S2" }],
      avionics: { primarySuite: "Analog + portable GPS" },
      maintenance: { logbooksComplete: true, currentlyAirworthy: true },
    },
    documents: [{ label: "Authority to Fly", status: "Available on request" }],
    verification: { photosVerified: true },
    marketEstimate: { available: true, minValue: 850_000, maxValue: 1_050_000, currency: "ZAR", marketPosition: "Fairly priced" },
    contact: { sellerType: "PRIVATE", contactName: "Private seller" },
  },
  {
    id: "lst-011",
    slug: "zs-efg-vans-rv-10",
    registration: "ZS-EFG",
    year: 2019,
    make: "Vans",
    model: "RV-10",
    category: "EXPERIMENTAL_NTCA",
    saleType: "MAKE_OFFER",
    publicStatus: "AVAILABLE",
    priceLabel: "Make an offer",
    currency: "ZAR",
    location: { airfield: "Wonderboom", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 520,
    engineTime: 520,
    seats: 4,
    engineCount: 1,
    registrationType: "ZU",
    avionicsSummary: "Garmin G3X",
    maintenanceSummary: "Builder maintained",
    highlights: ["Garmin G3X", "Experimental", "Low time", "Excellent performance"],
    images: images(IMG.sling, [IMG.cockpit, IMG.engine], "ZS-EFG"),
    listedAt: "2026-02-28T08:00:00.000Z",
    updatedAt: "2026-03-15T08:00:00.000Z",
    description: "Homebuilt RV-10 with G3X touch and Lycoming IO-540. Experimental category — buyers should review authority to fly requirements.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 520, registrationType: "ZU", category: "Experimental / NTCA" },
      engines: [{ position: "Centre", manufacturer: "Lycoming", model: "IO-540", timeSinceNew: 520 }],
      avionics: { primarySuite: "Garmin G3X Touch", efis: "G3X Touch" },
      maintenance: { logbooksComplete: true },
    },
    documents: [{ label: "Build logs", status: "Available on request" }],
    verification: { inspectionAvailable: true },
    marketEstimate: { available: false },
    contact: { sellerType: "PRIVATE", contactName: "Builder / owner" },
  },
  {
    id: "lst-012",
    slug: "zs-hij-baron-58",
    registration: "ZS-HIJ",
    year: 1998,
    make: "Beechcraft",
    model: "58",
    variant: "Baron",
    category: "MULTI_ENGINE_PISTON",
    saleType: "FIXED_PRICE",
    publicStatus: "AVAILABLE",
    price: 4_200_000,
    currency: "ZAR",
    location: { airfield: "Lanseria", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 5200,
    engineTime: 680,
    seats: 6,
    engineCount: 2,
    registrationType: "ZS",
    avionicsSummary: "IFR · Autopilot",
    maintenanceSummary: "Corporate maintained",
    highlights: ["Twin engine", "IFR equipped", "Autopilot", "Six seats"],
    images: images(IMG.beech, [IMG.cockpit, IMG.turboprop], "ZS-HIJ"),
    isVerified: true,
    listedAt: "2026-01-20T08:00:00.000Z",
    updatedAt: "2026-03-05T08:00:00.000Z",
    description: "Beechcraft Baron 58 for serious IFR travel. Twin Continental engines with recent top-end work.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 5200, category: "Multi Engine Piston" },
      engines: [
        { position: "Left", manufacturer: "Continental", model: "IO-550-C", timeSinceOverhaul: 680 },
        { position: "Right", manufacturer: "Continental", model: "IO-550-C", timeSinceOverhaul: 690 },
      ],
      avionics: { primarySuite: "Garmin GNS 530 + KFC 325", autopilot: "Bendix/King KFC 325" },
      maintenance: { logbooksComplete: true, currentlyAirworthy: true },
    },
    documents: [{ label: "Maintenance records", status: "Available to verified buyers" }],
    verification: { documentsReviewed: true, photosVerified: true },
    marketEstimate: { available: true, minValue: 3_900_000, maxValue: 4_500_000, currency: "ZAR", marketPosition: "Fairly priced" },
    contact: { sellerType: "BROKER", contactName: "Twin Aviation" },
  },
  {
    id: "lst-auct-001",
    slug: "zs-bon-beechcraft-g36",
    registration: "ZS-BON",
    year: 2014,
    make: "Beechcraft",
    model: "G36",
    variant: "Bonanza",
    category: "SINGLE_ENGINE_PISTON",
    saleType: "AUCTION",
    publicStatus: "AUCTION_SCHEDULED",
    currency: "ZAR",
    location: { airfield: "Grand Central", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 1420,
    engineTime: 420,
    engineTimeLabel: "SMOH",
    seats: 4,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "Garmin G1000 NXi",
    maintenanceSummary: "MPI current · Hangared",
    highlights: ["Garmin G1000 NXi", "Low engine time", "Hangared", "Complete logbooks"],
    images: images(IMG.beech, [IMG.cockpit, IMG.engine], "ZS-BON"),
    isVerified: true,
    isFeatured: true,
    listedAt: "2026-06-20T08:00:00.000Z",
    updatedAt: "2026-06-28T10:00:00.000Z",
    auction: {
      auctionId: "mock-auct-bon",
      phase: "SCHEDULED",
      openingBid: 3_800_000,
      currentBid: null,
      bidCount: 0,
      startsAt: "2026-07-05T10:00:00.000Z",
      effectiveEndsAt: "2026-07-07T18:00:00.000Z",
      showReserveStatus: true,
      reserveMet: false,
      biddingOpen: false,
    },
    description:
      "2014 Beechcraft G36 Bonanza scheduled for AVIATONLY timed auction. Full G1000 NXi suite, hangared at Grand Central, and complete maintenance records.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 1420, category: "Single Engine Piston" },
      engines: [{ position: "Centre", manufacturer: "Continental", model: "IO-550-B", timeSinceOverhaul: 420 }],
      avionics: { primarySuite: "Garmin G1000 NXi", autopilot: "Garmin GFC 700" },
      maintenance: { logbooksComplete: true, currentlyAirworthy: true, lastMpiDate: "2026-03-01" },
    },
    documents: [{ label: "Certificate of Registration", status: "Available on request" }],
    verification: { documentsReviewed: true, photosVerified: true, inspectionAvailable: true },
    marketEstimate: { available: true, minValue: 3_600_000, maxValue: 4_100_000, currency: "ZAR", marketPosition: "Market aligned" },
    contact: { sellerType: "AVIATONLY", contactName: "AVIATONLY Auctions" },
  },
  {
    id: "lst-auct-002",
    slug: "zs-sky-cessna-182t",
    registration: "ZS-SKY",
    year: 2008,
    make: "Cessna",
    model: "182T",
    variant: "Skylane",
    category: "SINGLE_ENGINE_PISTON",
    saleType: "AUCTION",
    publicStatus: "AUCTION_LIVE",
    currency: "ZAR",
    location: { airfield: "Wonderboom", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 2180,
    engineTime: 680,
    engineTimeLabel: "SMOH",
    seats: 4,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "Garmin G1000",
    maintenanceSummary: "MPI current",
    highlights: ["Live auction", "Garmin G1000", "IFR equipped", "Low engine time"],
    images: images(IMG.cessna172, [IMG.cockpit, IMG.engine], "ZS-SKY"),
    isVerified: true,
    isFeatured: true,
    listedAt: "2026-06-10T08:00:00.000Z",
    updatedAt: "2026-06-30T09:00:00.000Z",
    auction: {
      auctionId: "mock-auct-sky",
      phase: "LIVE",
      openingBid: 2_400_000,
      currentBid: 2_650_000,
      bidCount: 4,
      startsAt: "2026-06-28T10:00:00.000Z",
      effectiveEndsAt: "2026-07-03T20:00:00.000Z",
      showReserveStatus: true,
      reserveMet: false,
      biddingOpen: true,
    },
    description:
      "2008 Cessna 182T Skylane live on AVIATONLY auction with active bidding. Garmin G1000, IFR equipped, and recently reviewed by AVIATONLY ops.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 2180 },
      engines: [{ position: "Centre", manufacturer: "Lycoming", model: "IO-540-AB1A5", timeSinceOverhaul: 680 }],
      avionics: { primarySuite: "Garmin G1000" },
      maintenance: { logbooksComplete: true, currentlyAirworthy: true },
    },
    documents: [{ label: "Maintenance records", status: "Available to verified buyers" }],
    verification: { documentsReviewed: true, photosVerified: true },
    marketEstimate: { available: true, minValue: 2_500_000, maxValue: 2_900_000, currency: "ZAR", marketPosition: "Competitive" },
    contact: { sellerType: "AVIATONLY", contactName: "AVIATONLY Auctions" },
  },
  {
    id: "lst-auct-003",
    slug: "zs-mlb-piper-malibu",
    registration: "ZS-MLB",
    year: 2012,
    make: "Piper",
    model: "PA-46",
    variant: "Malibu",
    category: "SINGLE_ENGINE_PISTON",
    saleType: "AUCTION",
    publicStatus: "AVAILABLE",
    currency: "ZAR",
    location: { airfield: "Lanseria", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 2890,
    engineTime: 890,
    seats: 6,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "Garmin GTN 750",
    maintenanceSummary: "Corporate maintained",
    highlights: ["Pressurised", "Garmin GTN 750", "Six seats", "Auction ended"],
    images: images(IMG.piper, [IMG.cockpit, IMG.turboprop], "ZS-MLB"),
    isVerified: true,
    listedAt: "2026-05-01T08:00:00.000Z",
    updatedAt: "2026-06-28T18:00:00.000Z",
    auction: {
      auctionId: "mock-auct-mlb",
      phase: "ENDED",
      openingBid: 4_500_000,
      currentBid: 4_720_000,
      bidCount: 6,
      startsAt: "2026-06-20T10:00:00.000Z",
      effectiveEndsAt: "2026-06-28T18:00:00.000Z",
      showReserveStatus: true,
      reserveMet: true,
      biddingOpen: false,
    },
    description:
      "2012 Piper PA-46 Malibu — auction closed with reserve met. Pressurised six-seat touring aircraft with Garmin GTN 750.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 2890 },
      engines: [{ position: "Centre", manufacturer: "Continental", model: "TSIO-520-BE", timeSinceOverhaul: 890 }],
      avionics: { primarySuite: "Garmin GTN 750" },
      maintenance: { logbooksComplete: true },
    },
    documents: [{ label: "Logbook summary", status: "Available to verified buyers" }],
    verification: { documentsReviewed: true, photosVerified: true },
    marketEstimate: { available: true, minValue: 4_400_000, maxValue: 5_000_000, currency: "ZAR" },
    contact: { sellerType: "AVIATONLY", contactName: "AVIATONLY Auctions" },
  },
  {
    id: "lst-auct-004",
    slug: "zs-r44-robinson",
    registration: "ZS-R44",
    year: 2018,
    make: "Robinson",
    model: "R44",
    variant: "Raven II",
    category: "HELICOPTER",
    saleType: "AUCTION",
    publicStatus: "AVAILABLE",
    currency: "ZAR",
    location: { airfield: "Grand Central", province: "Gauteng", country: "South Africa" },
    totalTimeAirframe: 980,
    engineTime: 980,
    seats: 4,
    engineCount: 1,
    registrationType: "ZS",
    avionicsSummary: "Garmin G500H",
    maintenanceSummary: "MPI current",
    highlights: ["Helicopter", "Low time", "Garmin G500H", "Ended without reserve"],
    images: images(IMG.helicopter, [IMG.cockpit], "ZS-R44"),
    isVerified: true,
    listedAt: "2026-05-15T08:00:00.000Z",
    updatedAt: "2026-06-25T12:00:00.000Z",
    auction: {
      auctionId: "mock-auct-r44",
      phase: "ENDED",
      openingBid: 3_200_000,
      currentBid: 3_450_000,
      bidCount: 3,
      startsAt: "2026-06-18T10:00:00.000Z",
      effectiveEndsAt: "2026-06-25T16:00:00.000Z",
      showReserveStatus: false,
      reserveMet: null,
      biddingOpen: false,
    },
    description:
      "2018 Robinson R44 Raven II helicopter. Auction ended — reserve status hidden on public catalog per seller configuration.",
    technicalSpec: {
      airframe: { totalTimeAirframe: 980, category: "Helicopter" },
      engines: [{ position: "Centre", manufacturer: "Lycoming", model: "IO-540-AE1A5" }],
      avionics: { primarySuite: "Garmin G500H" },
      maintenance: { currentlyAirworthy: true },
    },
    documents: [{ label: "Maintenance records", status: "Available on request" }],
    verification: { photosVerified: true },
    marketEstimate: { available: false },
    contact: { sellerType: "AVIATONLY", contactName: "AVIATONLY Auctions" },
  },
];

export const MOCK_AIRCRAFT_LISTINGS: AircraftMarketplaceListing[] = MOCK_LISTINGS;

export function getMockListingBySlug(slug: string): AircraftMarketplaceDetail | undefined {
  return MOCK_LISTINGS.find((listing) => listing.slug === slug);
}

export function getMockListingSummaries(): AircraftMarketplaceListing[] {
  return MOCK_LISTINGS;
}

export function getMarketplaceStats() {
  const listings = MOCK_LISTINGS.filter((l) => l.publicStatus !== "SOLD");
  return {
    totalListings: listings.length,
    verifiedListings: listings.filter((l) => l.isVerified).length,
    fixedPriceCount: listings.filter((l) => l.saleType === "FIXED_PRICE").length,
    auctionCount: listings.filter((l) => l.saleType === "AUCTION").length,
  };
}
